/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sources;

/**
 *
 * @author User
 */
public class FoodPanel extends javax.swing.JPanel {
    private Food food;
    public int upperGap;
    public int y;
    /**
     * Creates new form FoodPanel
     */
    public FoodPanel(Food food) { //(Food food) as parameter
        initComponents();
        this.food = food;
        calValLabel.setText(String.format("%.2f", this.food.getCalories()));
        proValLabel.setText(String.format("%.2f", this.food.getProtein().getQuantity()));
        carbValLabel.setText(String.format("%.2f", this.food.getCarbohydrate().getQuantity()));
        fatValLabel.setText(String.format("%.2f", this.food.getFat().getQuantity()));
        fibreValLabel.setText(String.format("%.2f", this.food.getFibre().getQuantity()));
        saltValLabel.setText(String.format("%.2f", this.food.getSalt().getQuantity()));
        titleLabel.setText(food.getTitle());
    }
    public Food getFood(){
        return this.food;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        calValLabel = new javax.swing.JLabel();
        proValLabel = new javax.swing.JLabel();
        fatValLabel = new javax.swing.JLabel();
        carbValLabel = new javax.swing.JLabel();
        fibreValLabel = new javax.swing.JLabel();
        saltValLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(85, 85, 85));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calorie:");
        add(jLabel1);
        jLabel1.setBounds(20, 30, 43, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Carbohydrate:");
        add(jLabel4);
        jLabel4.setBounds(130, 30, 80, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Protein:");
        add(jLabel2);
        jLabel2.setBounds(20, 70, 44, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fat:");
        add(jLabel3);
        jLabel3.setBounds(20, 110, 30, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Salt:");
        add(jLabel5);
        jLabel5.setBounds(130, 110, 30, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fibre:");
        add(jLabel6);
        jLabel6.setBounds(130, 70, 31, 20);

        calValLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(calValLabel);
        calValLabel.setBounds(70, 30, 60, 20);

        proValLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(proValLabel);
        proValLabel.setBounds(70, 70, 60, 20);

        fatValLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(fatValLabel);
        fatValLabel.setBounds(70, 110, 60, 20);

        carbValLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(carbValLabel);
        carbValLabel.setBounds(220, 30, 70, 20);

        fibreValLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(fibreValLabel);
        fibreValLabel.setBounds(220, 70, 70, 20);

        saltValLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(saltValLabel);
        saltValLabel.setBounds(220, 110, 70, 20);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 83, 0));
        add(titleLabel);
        titleLabel.setBounds(30, 0, 100, 30);

        checkbox.setOpaque(false);
        add(checkbox);
        checkbox.setBounds(0, 0, 21, 21);
    }// </editor-fold>//GEN-END:initComponents
    public boolean isMarked(){
        return checkbox.isSelected();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calValLabel;
    private javax.swing.JLabel carbValLabel;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel fatValLabel;
    private javax.swing.JLabel fibreValLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel proValLabel;
    private javax.swing.JLabel saltValLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
