/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sources;


import javax.swing.ImageIcon;
import javax.swing.JProgressBar;


/**
 *
 * @author User
 */
public class ResultsPanel extends javax.swing.JFrame {
    private double totalEnergy;
    /**
     * Creates new form ResultsPanel
     */
    ImageIcon female = new ImageIcon(getClass().getResource("/icons/FemaleEmpty.png"));
    ImageIcon male = new ImageIcon(getClass().getResource("/icons/MaleEmpty.png"));
    public ResultsPanel() {
        initComponents();
        totalEnergy = SystemClass.calcTotalEnergy();
        if(SystemClass.user.getGender())
            progressIcon.setIcon(male);
        else
            progressIcon.setIcon(female);
        
        if((totalEnergy / SystemClass.user.calcDailyCalorieNeed() * 100) < 100)
            totalEnergyBar.setValue((int)(totalEnergy / SystemClass.user.calcDailyCalorieNeed() * 100));
        else
            totalEnergyBar.setValue(100);
        
        if((SystemClass.calcTotalProteinEnergy()/totalEnergy * 100) < 100)
            proteinEnergyBar.setValue((int)(SystemClass.calcTotalProteinEnergy()/SystemClass.calcTotalEnergy() * 100));
        else
            proteinEnergyBar.setValue(100);
        
        if((SystemClass.calcTotalCarbEnergy()/totalEnergy * 100) < 100)
            carbEnergyBar.setValue((int)(SystemClass.calcTotalCarbEnergy()/totalEnergy * 100));
        else
            carbEnergyBar.setValue(100);
            
        if(SystemClass.calcTotalEnergy() != 0 && (SystemClass.calcTotalFatEnergy()/totalEnergy * 100) < 100)
            fatEnergyBar.setValue((int)(SystemClass.calcTotalFatEnergy()/totalEnergy * 100));
        else
            fatEnergyBar.setValue(100);
        
        proteinNeedInfo.setText("%" + String.format("%.2f", SystemClass.calcTotalProteinEnergy() / SystemClass.user.calcDailyProteinNeed() * 100) + " of daily protein need");
        carbNeedInfo.setText("%" + String.format("%.2f", SystemClass.calcTotalCarbEnergy() / SystemClass.user.calcDailyCarbNeed() * 100) + " of daily carbohydrate need");
        fatNeedInfo.setText("%" + String.format("%.2f", SystemClass.calcTotalFatEnergy() / SystemClass.user.calcDailyFatNeed() * 100) + " of daily fat need");
        
        saturatedInfo.setText("%" + String.format("%.2f", SystemClass.calcTotalSaturatedFatEnergy() / SystemClass.user.calcDailyFatNeed() * 1000) + " of daily recommended saturated fat intake");
        fibreNeedInfo.setText("%" + String.format("%.2f", SystemClass.getTotalFibre() / SystemClass.user.calcDailyFibreNeed() * 100) + " of daily recommended fibre intake");
        saltInfo.setText("%" + String.format("%.2f", SystemClass.getTotalSalt()/ Salt.MAX_DAILY_SALT_GRAMS * 100) + " of daily salt limit");
        
        panelCalorieLbl.setText(String.format("%.2f", SystemClass.getHighestCalorieFood().getCalories()));
        panelProteinLbl.setText(String.format("%.2f", SystemClass.getHighestCalorieFood().getProtein().getQuantity()));
        panelCarbLbl.setText(String.format("%.2f", SystemClass.getHighestCalorieFood().getCarbohydrate().getQuantity()));
        panelFatLbl.setText(String.format("%.2f", SystemClass.getHighestCalorieFood().getFat().getQuantity()));
        panelFibreLbl.setText(String.format("%.2f", SystemClass.getHighestCalorieFood().getFibre().getQuantity()));
        panelSaltLbl.setText(String.format("%.2f", SystemClass.getHighestCalorieFood().getSalt().getQuantity()));
        panelTitleInfo.setText(SystemClass.getHighestCalorieFood().getTitle());
        
        calNeedLabel.setText(""+(int)SystemClass.user.calcDailyCalorieNeed() + " kcal");
        
        percentageLbl.setText("%" + (int)(SystemClass.calcTotalEnergy() / SystemClass.user.calcDailyCalorieNeed() * 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressIcon = new javax.swing.JLabel();
        emoteLbl = new javax.swing.JLabel();
        topIcon = new javax.swing.JLabel();
        percentageLbl = new javax.swing.JLabel();
        totalEnergyBar = new javax.swing.JProgressBar();
        proteinEnergyBar = new javax.swing.JProgressBar();
        carbEnergyBar = new javax.swing.JProgressBar();
        fatEnergyBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        biggestCalPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelCalorieLbl = new javax.swing.JLabel();
        panelProteinLbl = new javax.swing.JLabel();
        panelFatLbl = new javax.swing.JLabel();
        panelCarbLbl = new javax.swing.JLabel();
        panelFibreLbl = new javax.swing.JLabel();
        panelSaltLbl = new javax.swing.JLabel();
        panelTitleInfo = new javax.swing.JLabel();
        proteinNeedInfo = new javax.swing.JLabel();
        carbNeedInfo = new javax.swing.JLabel();
        fatNeedInfo = new javax.swing.JLabel();
        fibreNeedInfo = new javax.swing.JLabel();
        saltInfo = new javax.swing.JLabel();
        saturatedInfo = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        calNeedLabel = new javax.swing.JLabel();
        backgrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(progressIcon);
        progressIcon.setBounds(70, 180, 200, 300);

        emoteLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pepo.gif"))); // NOI18N
        emoteLbl.setText("jLabel1");
        jPanel1.add(emoteLbl);
        emoteLbl.setBounds(180, 40, 112, 112);

        topIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/matrix.gif"))); // NOI18N
        jPanel1.add(topIcon);
        topIcon.setBounds(0, 0, 1024, 150);

        percentageLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        percentageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(percentageLbl);
        percentageLbl.setBounds(113, 300, 110, 30);

        totalEnergyBar.setBackground(new java.awt.Color(255, 255, 255));
        totalEnergyBar.setForeground(new java.awt.Color(255, 51, 0));
        totalEnergyBar.setOrientation(1);
        totalEnergyBar.setToolTipText("Coverage of Daily Calorie Need");
        jPanel1.add(totalEnergyBar);
        totalEnergyBar.setBounds(90, 187, 160, 282);

        proteinEnergyBar.setToolTipText("Contribution to total energy");
        proteinEnergyBar.setStringPainted(true);
        jPanel1.add(proteinEnergyBar);
        proteinEnergyBar.setBounds(280, 190, 170, 70);

        carbEnergyBar.setToolTipText("Contribution to total energy");
        carbEnergyBar.setStringPainted(true);
        jPanel1.add(carbEnergyBar);
        carbEnergyBar.setBounds(280, 300, 170, 70);

        fatEnergyBar.setToolTipText("Contribution to total energy");
        fatEnergyBar.setStringPainted(true);
        jPanel1.add(fatEnergyBar);
        fatEnergyBar.setBounds(280, 400, 170, 70);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Protein Percentage:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 170, 140, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carbohydrate Percentage:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 280, 180, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fat Percentage:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 380, 170, 20);

        biggestCalPanel.setBackground(new java.awt.Color(102, 102, 102));
        biggestCalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "Food with the Biggest Calorie Value", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        biggestCalPanel.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Calorie:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Protein:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Fat:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Carbohydrate:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Fibre:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Salt:");

        panelCalorieLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        panelProteinLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        panelFatLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        panelCarbLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        panelFibreLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        panelSaltLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        panelTitleInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        panelTitleInfo.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout biggestCalPanelLayout = new javax.swing.GroupLayout(biggestCalPanel);
        biggestCalPanel.setLayout(biggestCalPanelLayout);
        biggestCalPanelLayout.setHorizontalGroup(
            biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biggestCalPanelLayout.createSequentialGroup()
                .addGroup(biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biggestCalPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCalorieLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelProteinLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelFatLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCarbLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelFibreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSaltLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                    .addGroup(biggestCalPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(panelTitleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        biggestCalPanelLayout.setVerticalGroup(
            biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biggestCalPanelLayout.createSequentialGroup()
                .addComponent(panelTitleInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(panelCalorieLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCarbLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(panelProteinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFibreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(biggestCalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(panelFatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSaltLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1.add(biggestCalPanel);
        biggestCalPanel.setBounds(80, 520, 400, 200);

        proteinNeedInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        proteinNeedInfo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(proteinNeedInfo);
        proteinNeedInfo.setBounds(560, 200, 380, 70);

        carbNeedInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        carbNeedInfo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(carbNeedInfo);
        carbNeedInfo.setBounds(560, 290, 380, 70);

        fatNeedInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fatNeedInfo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(fatNeedInfo);
        fatNeedInfo.setBounds(560, 380, 380, 70);

        fibreNeedInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fibreNeedInfo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(fibreNeedInfo);
        fibreNeedInfo.setBounds(510, 580, 510, 70);

        saltInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saltInfo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(saltInfo);
        saltInfo.setBounds(510, 660, 510, 70);

        saturatedInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saturatedInfo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(saturatedInfo);
        saturatedInfo.setBounds(510, 500, 510, 70);

        exitButton.setBackground(new java.awt.Color(153, 153, 153));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 0, 0));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton);
        exitButton.setBounds(660, 720, 130, 40);

        calNeedLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calNeedLabel.setForeground(new java.awt.Color(255, 0, 0));
        calNeedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(calNeedLabel);
        calNeedLabel.setBounds(100, 480, 140, 40);

        backgrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/grdbck.png"))); // NOI18N
        jPanel1.add(backgrd);
        backgrd.setBounds(-3, -4, 1200, 900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrd;
    private javax.swing.JPanel biggestCalPanel;
    private javax.swing.JLabel calNeedLabel;
    private javax.swing.JProgressBar carbEnergyBar;
    private javax.swing.JLabel carbNeedInfo;
    private javax.swing.JLabel emoteLbl;
    private javax.swing.JButton exitButton;
    private javax.swing.JProgressBar fatEnergyBar;
    private javax.swing.JLabel fatNeedInfo;
    private javax.swing.JLabel fibreNeedInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel panelCalorieLbl;
    private javax.swing.JLabel panelCarbLbl;
    private javax.swing.JLabel panelFatLbl;
    private javax.swing.JLabel panelFibreLbl;
    private javax.swing.JLabel panelProteinLbl;
    private javax.swing.JLabel panelSaltLbl;
    private javax.swing.JLabel panelTitleInfo;
    private javax.swing.JLabel percentageLbl;
    private javax.swing.JLabel progressIcon;
    private javax.swing.JProgressBar proteinEnergyBar;
    private javax.swing.JLabel proteinNeedInfo;
    private javax.swing.JLabel saltInfo;
    private javax.swing.JLabel saturatedInfo;
    private javax.swing.JLabel topIcon;
    private javax.swing.JProgressBar totalEnergyBar;
    // End of variables declaration//GEN-END:variables
}
